adding rubocop to test execution and rubo_fix helper

diff --git a/bin/run_tests b/bin/run_tests
--- a/bin/run_tests
+++ b/bin/run_tests
@@ -8,3 +8,12 @@ if [ $? -ne 0 ]; then
     echo -e "\n== Tests failed; push aborted! ==\n"
     exit 1
 fi
+
+echo "== Starting rubocop =="
+bundle exec rubocop --format worst --format simple --format offenses
+if [ $? -ne 0 ]; then
+    echo -e "\n== Rubocop failed; push aborted! ==\n"
+    echo -e "To auto-correct errors run:"
+    echo -e "\tbin/rubo_fix"
+    exit 1
+fi
